### ISSUE TITLE
Explore adding top-level "API" link to header nav

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#171]
[This discussion thread on Twitter](https://twitter.com/LedZ3pp/status/919923967787458565) provided feedback that the reference section of the docs may be too buried given the new website's accordion sidebar.

@gaearon proposed we could do something similar to what [Jest](http://facebook.github.io/jest/) and add an "API" link to the header that directly opens the first page of the reference section (eg [React Top-Level API](https://reactjs.org/docs/react-api.html)).

Unfortunately this is a little more complicated than it would seem at a glance because of:
* [How we determine which header link gets the "active" style](https://github.com/reactjs/reactjs.org/blob/e826e307e0c129a478546c79030518a9ee311389/src/components/LayoutHeader/Header.js#L117). (Jest side-steps this issue by not applying "active" header link styles.)
* A symmetry we try to maintain between the [location of markdown content](https://github.com/reactjs/reactjs.org/tree/e826e307e0c129a478546c79030518a9ee311389/content) (eg content/blog, content/docs) and the top-level nav structure (eg "Blog", "Docs")

We _could_ move things around so that reference links have a unique URL prefix, but we'd need to leave backwards-compatible redirects in place so that no bookmarked links were broken.

Unfortunately we can't rely on anything dynamic (like markdown frontmatter tags) for this because the header and footer are part of the "static" Gatsby layout. (Technically we could move them into the templates but this doesn't seem ideal.)

**Comment by KyleAMathews** [comment]
You could just make the active style programmatic right? Just say any reference doc pages make the API header link active.

Perhaps removing the accordion is an option too?

**Comment by bvaughn** [comment]
> You could just make the active style programmatic right? Just say any reference doc pages make the API header link active.

We _could_ but that's what this section from the description was referencing:

> Unfortunately we can't rely on anything dynamic (like markdown frontmatter tags) to help with the "active" link styling because the header and footer are part of the "static" Gatsby layout. (Technically we could move them into the templates but this doesn't seem ideal.)

Short of moving the header out of the layout _or_ hard-coding a bunch of URLs in it- how would you propose we do this?

**Comment by KyleAMathews** [comment]
>hard-coding a bunch of URLs

done! https://github.com/reactjs/reactjs.org/blob/master/content/docs/nav.yml :-)

**Comment by bvaughn** [comment]
Reading between the lines, what you're suggesting seems a bit janky to me.

It would require us to embed nav YML files in the layout component (rather than their template) and do pattern matching based on file names (which might cause conflicts) rather than the root of the URL.

I guess we could combine both techniques (root of the URL + filename) but I still don't like the nav YMLs being used in the layout.

**Comment by KyleAMathews** [comment]
Yeah, you'd import the docs yaml file into the layout component and there, check the current pathname against the list of paths in the yaml file. If the path is in the reference section, you highlight "API".

**Comment by bvaughn** [comment]
Sure, I understand what you're proposing 😄  it just seems janky to me.

**Comment by KyleAMathews** [comment]
Give it five minutes Brian! ;-)

**Comment by jxom** [comment]
@bvaughn - what if another route /api is added, and that route references the 'Reference' category in /docs (could rename this to API Reference imo)? So that the 'API Reference' content is in /docs still, but also in /api?

**Comment by jxom** [comment]
@bvaughn @KyleAMathews - what if a `content/api` folder (and hence an 'API' nav item) is added, whereby the 'Reference' content in `content/docs` is moved to this new `content/api` folder. And perhaps the Docs page could reference the content in `content/api` for the 'Reference' section? Could do this by `content/docs/nav.yml` referencing `content/api/nav.yml` somehow? That's my two cents. 🤷‍♀️ Hope it makes sense! (that rhymes 😎)
