### ISSUE TITLE
Can't scroll sidebar

### ISSUE THREAD

**Issue by SihamBen** [reactjs/reactjs.org#3374]
Can't scroll the sidebar, so it's impossible to see subsections with it surpasses the screen height

**Comment by joshtom** [comment]
Hello, @SihamBen are you talking about the react JS docs?

**Comment by SihamBen** [comment]
Yes

**Comment by joshtom** [comment]
Each subsection of the sidebar is collapsible and you can view the content by clicking on it. I just tried it and It's scrolling if the content is more than the height. But it would be better if you could share a screenshot if this doesn't answer your question.

**Comment by SihamBen** [comment]
As you can see here I'm unable to scroll to see the rest of the Hooks subsections
![Uploading Capture.JPG…]()

**Comment by joshtom** [comment]
> As you can see here I'm unable to scroll to see the rest of the Hooks subsections

The image doesn't seem to upload correctly

**Comment by SihamBen** [comment]
I've Fixed it

**Comment by joshtom** [comment]
This bug is not related to the react website probably, It's your machine you need to check. 

Cause I could see everything clearly from my end. 
![image](https://user-images.githubusercontent.com/42160061/98434742-9e8a0b00-20d2-11eb-8f06-bfee0229252a.png)

**Comment by ondrejpar** [comment]
I have the same problem (on multiple computers, different browsers).
The content is there, but scrolling the page does not scroll the sidebar - it's fixed. So, if the content of sidebar is higher than browser window, I can't access bottom links.
Either the sidebar should have its own scrollbar, or it should scroll with the rest of the page (I prefer the latter).

**Comment by SihamBen** [comment]
Apparently the problem is ralated to my device

**Comment by ondrejpar** [comment]
I'm still experiencing the same problem on Firefox 83.0 (currently the latest version).
